on:
  pull_request_target:
    types:
      - "opened"
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  comment_pull_request:
    runs-on: ubuntu-latest
    permissions:
      # Needed to write comments in the pull request
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Really important to get the good commit
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: 0

      - name: Perform semantic version
        uses: paulhatch/semantic-version@v5.0.3
        id: semantic_version
        with:
          tag_prefix: "alpha-"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
          user_format_type: "csv"
          bump_each_commit: false
          search_commit_body: true

      - name: Comment PR
        # Github action used to write pull request comments
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: The next version will be **${{ steps.semantic_version.outputs.version_tag }}** ! :rocket:

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ steps.semantic_version.outputs.version_tag }}
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
