name: CI/CD Workflow

on:
  pull_request_target:
    types:
      - "opened"
    branches:
      - develop

env:
  ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

jobs:
  comment_pull_request:
    runs-on: ubuntu-latest
    permissions:
      # Needed to write comments in the pull request
      pull-requests: write
      contents: write # Needed to push tags

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}

      - name: Bump version
        uses: PaulHatch/semantic-version@v4.0.2
        id: tag_version_develop
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          format: "${major}.${minor}.${patch}"
          namespace: develop
          change_path: "."
          short_tags: false
          bump_each_commit: true

      - name: Tag Release (vX.Y.Z)
        run: |
          git tag ${{ steps.tag_version_develop.outputs.version_tag }}
          git push origin ${{ steps.tag_version_develop.outputs.version_tag }}
