on:
  pull_request_target:
    types:
      - "opened"
    branches:
      - develop

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  comment_pull_request:
    runs-on: ubuntu-latest
    permissions:
      # Needed to write comments in the pull request
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Bump version
        uses: PaulHatch/semantic-version@v4.0.2
        id: tag_version_develop
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          format: "${major}.${minor}.${patch}"
          namespace: develop
          change_path: "."
          short_tags: false
          bump_each_commit: true
      - name: Tag Release (vX.Y.Z)
        run: |
          git tag ${{ steps.tag_version_develop.outputs.version_tag }}
          git push origin ${{ steps.tag_version_develop.outputs.version_tag }}
